### ISSUE TITLE
1.17.1 Compatibility

### ISSUE THREAD

**Issue by ersamson** [haykam821/Raised-Clouds#3]
If you can port this for 1.17.1, please?

I'm basically a noob when in comes to modding.  But I have managed to gradle build this using latest Fabric yarn, Java 16 compatibility among other "up versions"

It's the "WorldRendererMixin.java" that the code having trouble with, especially starting on the injection on line 32.  As I can't find any reference so I can inject cloud height Y.

> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method getCloudY(D)D in raisedclouds.mixin.json:WorldRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s).

**Comment by haykam821** [comment]
[Version 1.1.0](https://github.com/haykam821/Raised-Clouds/releases/tag/1.1.0) supports Minecraft 1.17.1.
