### ISSUE TITLE
The Latest Version of the Mod Crashes Minecraft When Running it With Fabric Modloader for 1.19.3

### ISSUE THREAD

**Issue by Snick2014** [haykam821/Raised-Clouds#5]
Using Fabric Modloader for 1.19.3, and no incompatible mods, the latest version of this mod (which is for 1.19.2) always crashes my installation of the game (which uses the vanilla launcher), and gives the following crash description:

"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed"

**Comment by Snick2014** [comment]
When trying to use the mod in 1.19.2 instead, it says it's incompatible, and a suggested possible solution is to download "cloth-config 2" - I have Cloth Config API (https://modrinth.com/mod/cloth-config) installed, but I haven't seen any mention of a "Cloth Config 2" online anywhere even when searching for the term.

**Comment by Rektroth** [comment]
[Updated build](https://github.com/Rektroth/Raised-Clouds-1.19.3/releases/tag/1.2.1-pre1) you can use until haykam releases it himself.

**Comment by Snick2014** [comment]
Ah - wonderful - thank you!

**Comment by haykam821** [comment]
[Version 1.3.0](https://github.com/haykam821/Raised-Clouds/releases/tag/1.3.0) supports Minecraft 1.19.3.
