### ISSUE TITLE
why the clouds cant lower than 192 ?? 

### ISSUE THREAD

**Issue by xiaoxiaogtlao** [haykam821/Raised-Clouds#7]
i hope i could set the height to 128 which is the old version, because nostalgia
can u help me get my childhood back?

**Comment by haykam821** [comment]
Could you take a screenshot of the configuration screen?

**Comment by xiaoxiaogtlao** [comment]
@haykam821  still on y=192
![屏幕截图 2024-10-02 225727](https://github.com/user-attachments/assets/cd29b3e3-e0c6-4906-8f96-6f1d2016cc70)
![屏幕截图 2024-10-02 225818](https://github.com/user-attachments/assets/b23caddd-86fa-47cb-b5b9-f85862b17b32)
![363209085-9d2fa01b-9349-4256-9606-42e49b4f2c53](https://github.com/user-attachments/assets/bb800095-f318-4983-8411-ded94a0f4a0a)

**Comment by xiaoxiaogtlao** [comment]
1.3.1

**Comment by haykam821** [comment]
You should enable 'Override Base Y'.

**Comment by xiaoxiaogtlao** [comment]
ty
